#!/bin/bash

# clear 
# while getopts d:c:a: option
# do
# case "${option}"
# in
# d) DATA=${OPTARG};;
# c) CONTAINER=${OPTARG};;
# p) AGGREGATOR=${OPTARG};;
# esac
# done
SCONE_MODE=AUTO
pip3 install requests
echo $DATA
python3 user_enclave_scripts.py "$1" "$2" "$3"